version: "3"
services:
  app:
    container_name: cenote-api
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mongodb://mongo:27017/cenote-db
      - PORT=3000
      - HOST=0.0.0.0
      - GLOBAL_LIMIT=5000
      - KAFKA_SERVERS=83.212.104.172:9092,83.212.96.15:9092,155.207.19.38:9092
      - KAFKA_TOPIC=cenoteIncoming
      - COCKROACH_URL=155.207.19.234
      - COCKROACH_PORT=30591
      - REDIS_URL=	83.212.96.15
      - REDIS_PORT=6379
      - COCKROACH_DBNAME=cenote
      - COOKIE_SECRET=cenote-secret
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
