version: "3.6"
services:
  web:
    container_name: web
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://mongo:27017/cenote-db
      - HOST=0.0.0.0
    command: npm start
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
